# Generated by Django 5.1.3 on 2024-11-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_name_customer_first_name_customer_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
